### PR TITLE
Added translation to Spanish

### PR DESCRIPTION
**Pull request by chrisgalvan**

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Hi @chrisgalvan, thanks for the contribution.
@vmmartinezlona sent a PR in #7, but with wrong folder name. I will wait for her first. You can improve her translation too.

**Comment by rodrigo-brito** [comment]
What is your country? Maybe we can use both.

**Comment by chrisgalvan** [comment]
Mexico.

**Comment by rodrigo-brito** [comment]
@chrisgalvan I accept the PR #7, you can suggest corrections too.

**Pull request closed without merging**
