### PR TITLE
Remove English from Norwegian language file

### PR DESCRIPTION
**Pull request by 058c37a272bed3464d47f0b01038a16a**
Looks like some English snuck into the Norwegian language file, so I removed it!
# hacktoberfest

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Thanks for the contribution @RainoBoy97 !

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
Could I have the Hacktoberfest label to contribute towards a t-shirt? 😄

**Comment by rodrigo-brito** [comment]
The hacktoberfest goes for all repositories of GitHub, the label only helps to identify the issues and more engaged projects.

**Comment by rodrigo-brito** [comment]
I include, but is not necessary.

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
Oh, I did not know that. Thanks!

**Pull request merged**
