### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by vmmartinezlona**

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
The abreviation of spanish is "es" instead of "sp", please rename the folder!

**Comment by rodrigo-brito** [comment]
Whats is your country @vmmartinezlona?

**Comment by vmmartinezlona** [comment]
I'm from México, here we use "sp" for spanish, sorry for the error

**Comment by rodrigo-brito** [comment]
No problem! Gracias for the contribution!

**Pull request merged**
