### PR TITLE
Add bengali translations

### PR DESCRIPTION
**Pull request by evijit**
Added translations for the Bengali language as requested in Issue #1 .

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Hi @AvijitGhosh82, thanks for the contribution. Can you complete the description?

**Comment by evijit** [comment]
@rodrigo-brito Done!

**Comment by rodrigo-brito** [comment]
I said the "description" field in translation file!

**Comment by rodrigo-brito** [comment]
Thank you!

**Pull request merged**
